/**
 * Norwegian (nb-NO) localization strings.
 * Minimal set for MVP - no i18n library overhead.
 */

export const TEXT = {
  app: {
    title: 'Beslutningsstøtte',
    disclaimer: 'Beslutningsstøtte – ikke medisinsk beslutning',
    disclaimerFull:
      'Dette verktøyet er kun til beslutningsstøtte. Det erstatter ikke klinisk vurdering eller medisinsk ansvar. All bruk skjer på eget ansvar.',
  },
  navigation: {
    drugLibrary: 'Legemiddelbibliotek',
    taperingPlanner: 'Nedtrappingsplanlegger',
    settings: 'Innstillinger',
  },
  drugLibrary: {
    title: 'Legemiddelbibliotek',
    addDrug: 'Legg til legemiddel',
    editDrug: 'Rediger legemiddel',
    deleteDrug: 'Slett legemiddel',
    noDrugs: 'Ingen legemidler registrert',
    confirmDelete: 'Er du sikker på at du vil slette dette legemidlet?',
  },
  drugForm: {
    name: 'Navn',
    activeSubstance: 'Virkestoff',
    halfLife: 'Halveringstid (timer)',
    standardDose: 'Standarddose (mg)',
    notes: 'Notater',
    save: 'Lagre',
    cancel: 'Avbryt',
    required: 'Påkrevd',
    mustBePositive: 'Må være positiv',
    searchFK: 'Søk i Felleskatalogen',
    searchFKHint: 'Åpner Felleskatalogen i nytt vindu for å finne informasjon',
  },
  taperingPlanner: {
    title: 'Nedtrappingsplanlegger',
    selectDrug: 'Velg legemiddel',
    addDrug: 'Legg til legemiddel',
    removeDrug: 'Fjern',
    startingDose: 'Startdose (mg)',
    targetDose: 'Måldose (mg)',
    reductionMg: 'Reduksjon per steg (mg)',
    intervalDays: 'Dager mellom hvert steg',
    calculate: 'Beregn nedtrapping',
    generateNote: 'Generer journalnotat',
    schedule: 'Nedtrappingsplan',
    combinedSchedule: 'Kombinert oversikt',
    step: 'Steg',
    dose: 'Dose',
    duration: 'Varighet',
    days: 'dager',
    totalDuration: 'Total varighet',
    noSchedule: 'Ingen plan beregnet ennå',
    noDrugsSelected: 'Ingen legemidler valgt. Legg til ett eller flere legemidler.',
  },
  riskTag: {
    low: 'Lav risiko',
    medium: 'Moderat risiko',
    high: 'Høy risiko',
  },
  journalNote: {
    title: 'Journalnotat',
    copy: 'Kopier til utklippstavle',
    copied: 'Kopiert!',
    indication: 'Indikasjon',
    plan: 'Nedtrappingsplan',
    interactions: 'Interaksjonsrisiko',
    additionalNotes: 'Tilleggsnotater',
  },
  common: {
    save: 'Lagre',
    cancel: 'Avbryt',
    delete: 'Slett',
    edit: 'Rediger',
    close: 'Lukk',
    confirm: 'Bekreft',
    search: 'Søk',
    loading: 'Laster...',
    error: 'Feil',
    success: 'Suksess',
  },
  errors: {
    requiredField: 'Dette feltet er påkrevd',
    invalidNumber: 'Ugyldig tall',
    mustBePositive: 'Må være større enn 0',
    targetMustBeLower: 'Måldose må være lavere enn startdose',
    databaseError: 'Databasefeil',
    calculationError: 'Beregningsfeil',
  },
};
